# Generated by Django 4.1.5 on 2023-01-10 06:56

import Store.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120)),
                ('image', models.ImageField(blank=True, null=True, upload_to=Store.models.get_path_img)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=False, help_text='0=default , 1=hidden')),
                ('tranding', models.BooleanField(default=False, help_text='0 = default , 1=Trading')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120)),
                ('image', models.ImageField(blank=True, null=True, upload_to=Store.models.get_path_img)),
                ('shortdes', models.TextField(blank=True, null=True)),
                ('quntity', models.IntegerField()),
                ('price', models.FloatField()),
                ('offer', models.FloatField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=False, help_text='0=default , 1=hidden')),
                ('tranding', models.BooleanField(default=False, help_text='0 = default , 1=Trading')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.category')),
            ],
        ),
    ]
