# Generated by Django 4.1.5 on 2023-01-10 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0002_remove_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
    ]
