# Generated by Django 4.1.5 on 2023-01-10 15:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0003_remove_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
