# Generated by Django 4.1.5 on 2023-01-10 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0004_product_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='size',
            new_name='rate',
        ),
    ]
